# Generated by Django 6.0.3 on 2026-03-27 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiVanBan',
            fields=[
                ('ma_loai_vb', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ten_loai_vb', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Loại văn bản',
                'verbose_name_plural': 'Loại văn bản',
                'db_table': 'LoaiVanBan',
                'ordering': ['ten_loai_vb'],
            },
        ),
        migrations.CreateModel(
            name='MucDoUuTien',
            fields=[
                ('ma_muc_do', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('muc_do', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Mức độ ưu tiên',
                'verbose_name_plural': 'Mức độ ưu tiên',
                'db_table': 'Mucdouutien',
                'ordering': ['ma_muc_do'],
            },
        ),
        migrations.CreateModel(
            name='VaiTro',
            fields=[
                ('ma_vai_tro', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ten_vai_tro', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Vai trò',
                'verbose_name_plural': 'Vai trò',
                'db_table': 'Vaitro',
                'ordering': ['ten_vai_tro'],
            },
        ),
        migrations.CreateModel(
            name='GiaoVien',
            fields=[
                ('ma_gv', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(max_length=150)),
                ('trang_thai_tk', models.CharField(default='Hoạt động', max_length=50)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ho_so_giao_vien', to=settings.AUTH_USER_MODEL)),
                ('ma_vai_tro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='giao_viens', to='QLVBDH.vaitro')),
            ],
            options={
                'verbose_name': 'Giáo viên',
                'verbose_name_plural': 'Giáo viên',
                'db_table': 'GiaoVien',
                'ordering': ['ho_ten'],
            },
        ),
        migrations.CreateModel(
            name='MauVanBan',
            fields=[
                ('ma_mau_vb', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ten_mau', models.CharField(max_length=100)),
                ('file_mau', models.FileField(upload_to='mau_van_ban/')),
                ('trang_thai', models.CharField(default='Đang sử dụng', max_length=100)),
                ('ma_loai_vb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mau_van_bans', to='QLVBDH.loaivanban')),
            ],
            options={
                'verbose_name': 'Mẫu văn bản',
                'verbose_name_plural': 'Mẫu văn bản',
                'db_table': 'MauVanBan',
                'ordering': ['ten_mau'],
            },
        ),
        migrations.CreateModel(
            name='VanBanDen',
            fields=[
                ('so_vb_den', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('co_quan_ban_hanh', models.CharField(max_length=100)),
                ('so_ky_hieu', models.CharField(max_length=15)),
                ('ngay_ky', models.DateField()),
                ('trich_yeu', models.CharField(max_length=500)),
                ('file_van_ban', models.FileField(upload_to='van_ban_den/')),
                ('trang_thai_vb_den', models.CharField(default='Mới tiếp nhận', max_length=100)),
                ('ngay_nhan', models.DateField()),
                ('ma_loai_vb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='van_ban_dens', to='QLVBDH.loaivanban')),
                ('ma_muc_do', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='van_ban_dens', to='QLVBDH.mucdouutien')),
            ],
            options={
                'verbose_name': 'Văn bản đến',
                'verbose_name_plural': 'Văn bản đến',
                'db_table': 'VanBanDen',
                'ordering': ['-ngay_nhan', '-ngay_ky'],
            },
        ),
        migrations.CreateModel(
            name='VanBanDi',
            fields=[
                ('so_vb_di', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('so_ky_hieu', models.CharField(max_length=15)),
                ('trich_yeu', models.CharField(max_length=500)),
                ('ngay_ky', models.DateField(blank=True, null=True)),
                ('noi_nhan', models.CharField(max_length=100)),
                ('ban_du_thao', models.FileField(upload_to='van_ban_di/du_thao/')),
                ('ban_chinh_thuc', models.FileField(blank=True, null=True, upload_to='van_ban_di/chinh_thuc/')),
                ('trang_thai_vb_di', models.CharField(default='Soạn thảo', max_length=50)),
                ('ngay_ban_hanh', models.DateField(blank=True, null=True)),
                ('ma_loai_vb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='van_ban_dis', to='QLVBDH.loaivanban')),
                ('ma_muc_do', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='van_ban_dis', to='QLVBDH.mucdouutien')),
                ('nguoi_ky', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='van_ban_da_ky', to='QLVBDH.giaovien')),
                ('nguoi_tao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='van_ban_da_tao', to='QLVBDH.giaovien')),
            ],
            options={
                'verbose_name': 'Văn bản đi',
                'verbose_name_plural': 'Văn bản đi',
                'db_table': 'VanBanDi',
                'ordering': ['-ngay_ban_hanh', '-ngay_ky'],
            },
        ),
        migrations.CreateModel(
            name='PhanCongXuLy',
            fields=[
                ('ma_xu_ly', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('noi_dung_cd', models.CharField(max_length=500)),
                ('thoi_han', models.DateField()),
                ('trang_thai_xl', models.CharField(default='Chưa xử lý', max_length=100)),
                ('nguoi_xu_ly', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phan_cong_xu_lys', to='QLVBDH.giaovien')),
                ('so_vb_den', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phan_congs', to='QLVBDH.vanbanden')),
                ('so_vb_di', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phan_congs', to='QLVBDH.vanbandi')),
            ],
            options={
                'verbose_name': 'Phân công xử lý',
                'verbose_name_plural': 'Phân công xử lý',
                'db_table': 'PhanCongXuLy',
                'ordering': ['thoi_han'],
            },
        ),
        migrations.CreateModel(
            name='NhatKyVanBan',
            fields=[
                ('ma_nhat_ky', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('yc_chinh_sua', models.CharField(blank=True, max_length=500)),
                ('trang_thai', models.CharField(max_length=100)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True)),
                ('ma_nguoi_tao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nhat_kys', to='QLVBDH.giaovien')),
                ('ma_vb_den', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nhat_kys', to='QLVBDH.vanbanden')),
                ('ma_vb_di', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nhat_kys', to='QLVBDH.vanbandi')),
            ],
            options={
                'verbose_name': 'Nhật ký văn bản',
                'verbose_name_plural': 'Nhật ký văn bản',
                'db_table': 'NhatKyVanBan',
                'ordering': ['-thoi_gian_tao'],
            },
        ),
    ]
