# Generated by Django 6.0.3 on 2026-03-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLVBDH', '0002_admin_group_and_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhatkyvanban',
            name='ma_nhat_ky',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='phancongxuly',
            name='ma_xu_ly',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='so_vb_den',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='so_vb_di',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False),
        ),
    ]
