# Generated by Django 6.0.3 on 2026-03-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLVBDH', '0003_alter_nhatkyvanban_ma_nhat_ky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaivanban',
            name='ma_loai_vb',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mauvanban',
            name='ma_mau_vb',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mucdouutien',
            name='ma_muc_do',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vaitro',
            name='ma_vai_tro',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False),
        ),
    ]
