# Generated by Django 6.0.3 on 2026-03-27 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLVBDH', '0005_sync_role_groups_and_teacher_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhomVaiTro',
            fields=[
                ('ma_nhom_vai_tro', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('ten_nhom_vai_tro', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Nhóm vai trò',
                'verbose_name_plural': 'Nhóm vai trò',
                'db_table': 'NhomVaiTro',
                'ordering': ['ten_nhom_vai_tro'],
            },
        ),
        migrations.AddField(
            model_name='vaitro',
            name='nhom_vai_tro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vai_tros', to='QLVBDH.nhomvaitro'),
        ),
    ]
