# Generated by Django 6.0.3 on 2026-03-29 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLVBDH', '0010_loaivanban_ap_dung'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToChuyenMon',
            fields=[
                ('ma_to', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('ten_to', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tổ chuyên môn',
                'verbose_name_plural': 'Tổ chuyên môn',
                'db_table': 'ToChuyenMon',
                'ordering': ['ten_to'],
            },
        ),
        migrations.AddField(
            model_name='giaovien',
            name='ma_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='giao_viens', to='QLVBDH.tochuyenmon'),
        ),
    ]
