# Generated by Django 6.0.3 on 2026-03-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLVBDH', '0012_nguoiduyet'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaivanban',
            name='ten_viet_tat',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vanbandi',
            name='so_thu_tu',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='so_ky_hieu',
            field=models.CharField(max_length=50),
        ),
    ]
