# Generated by Django 6.0.3 on 2026-03-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLVBDH', '0013_loaivanban_ten_viet_tat_vanbandi_so_thu_tu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xuly',
            name='vai_tro_ky',
            field=models.CharField(choices=[('ky_nhay', 'Ký nháy'), ('ky_chinh', 'Ký chính')], max_length=20),
        ),
    ]
