# Generated by Django 6.0.3 on 2026-03-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLVBDH', '0014_alter_xuly_vai_tro_ky'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaivanban',
            name='twocap',
            field=models.IntegerField(choices=[(0, '1 cap'), (1, '2 cap')], default=0),
        ),
    ]
