# Generated by Django 6.0.3 on 2026-03-29 10:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLVBDH', '0015_loaivanban_twocap'),
    ]

    operations = [
        migrations.AddField(
            model_name='mauvanban',
            name='muc_dich',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mauvanban',
            name='ngay_tao',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='mauvanban',
            name='trang_thai',
            field=models.CharField(choices=[('Dang su dung', 'Dang su dung'), ('Dung su dung', 'Dung su dung'), ('Du thao', 'Du thao')], default='Dang su dung', max_length=100),
        ),
    ]
