# Generated by Django 4.2.8 on 2026-03-29 13:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('QLVBDH', '0016_mauvanban_muc_dich_mauvanban_ngay_tao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phancongxuly',
            name='nguoi_phan_cong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phan_cong_da_giao', to='QLVBDH.giaovien'),
        ),
        migrations.AddField(
            model_name='phancongxuly',
            name='thoi_gian_phan_cong',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='phancongxuly',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('so_vb_den__isnull', False), ('so_vb_di__isnull', True)), models.Q(('so_vb_den__isnull', True), ('so_vb_di__isnull', False)), _connector='OR'), name='phan_cong_exactly_one_document'),
        ),
        migrations.AddConstraint(
            model_name='phancongxuly',
            constraint=models.UniqueConstraint(condition=models.Q(('so_vb_den__isnull', False)), fields=('so_vb_den', 'nguoi_xu_ly'), name='uniq_phan_cong_vb_den_nguoi_xu_ly'),
        ),
        migrations.AddConstraint(
            model_name='phancongxuly',
            constraint=models.UniqueConstraint(condition=models.Q(('so_vb_di__isnull', False)), fields=('so_vb_di', 'nguoi_xu_ly'), name='uniq_phan_cong_vb_di_nguoi_xu_ly'),
        ),
    ]
