# Generated by Django 6.0.3 on 2026-04-08 07:15

from django.db import migrations, models


def copy_role_name_to_position(apps, schema_editor):
    GiaoVien = apps.get_model("QLVBDH", "GiaoVien")

    for giao_vien in GiaoVien.objects.prefetch_related("vai_tros").all():
        first_role = giao_vien.vai_tros.order_by("ten_vai_tro").values_list("ten_vai_tro", flat=True).first() or ""
        if first_role:
            giao_vien.chuc_vu = first_role
            giao_vien.save(update_fields=["chuc_vu"])


class Migration(migrations.Migration):

    dependencies = [
        ('QLVBDH', '0020_alter_tochuyenmon_to_truong'),
    ]

    operations = [
        migrations.AddField(
            model_name='giaovien',
            name='chuc_vu',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.RunPython(copy_role_name_to_position, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='giaovien',
            name='vai_tros',
        ),
        migrations.AlterField(
            model_name='mauvanban',
            name='trang_thai',
            field=models.CharField(choices=[('Dang su dung', 'Đang sử dụng'), ('Dung su dung', 'Dừng sử dụngg'), ('Du thao', 'Dự thảo')], default='Dang su dung', max_length=100),
        ),
        migrations.DeleteModel(
            name='VaiTro',
        ),
    ]
