# Generated by Django 6.0.3 on 2026-04-12 06:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLVBDH', '0021_remove_giaovien_vai_tros_giaovien_chuc_vu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoiNhan',
            fields=[
                ('ma_noi_nhan', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('ten_noi_nhan', models.CharField(max_length=200, unique=True)),
                ('dia_chi', models.CharField(blank=True, max_length=255)),
                ('so_dien_thoai', models.CharField(blank=True, max_length=20)),
                ('gmail', models.EmailField(blank=True, max_length=254)),
                ('thong_tin_khac', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'NoiNhan',
                'ordering': ['ten_noi_nhan'],
            },
        ),
        migrations.AlterField(
            model_name='xuly',
            name='vai_tro_ky',
            field=models.CharField(choices=[('ky_nhay', 'Ky nhay'), ('ky_chinh', 'Ky chinh'), ('ky_thay', 'Ky thay')], max_length=20),
        ),
        migrations.CreateModel(
            name='LuanChuyenBenNgoai',
            fields=[
                ('ma_luan_chuyen', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('thoi_gian_gui', models.DateTimeField(default=django.utils.timezone.now)),
                ('trang_thai_gui', models.CharField(choices=[('Da gui', 'Da gui'), ('Gui loi', 'Gui loi'), ('Cho gui', 'Cho gui')], default='Da gui', max_length=50)),
                ('ghi_chu', models.CharField(blank=True, max_length=500)),
                ('ma_vb_di', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luan_chuyen_ben_ngoais', to='QLVBDH.vanbandi')),
                ('nguoi_thuc_hien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='luan_chuyen_ben_ngoai_da_tao', to='QLVBDH.giaovien')),
                ('ma_noi_nhan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='luan_chuyen_ben_ngoais', to='QLVBDH.noinhan')),
            ],
            options={
                'db_table': 'LuanChuyenBenNgoai',
                'ordering': ['-thoi_gian_gui', 'ma_luan_chuyen'],
                'constraints': [models.UniqueConstraint(fields=('ma_vb_di', 'ma_noi_nhan'), name='uniq_luan_chuyen_vb_di_noi_nhan')],
            },
        ),
    ]
