# Generated by Django 6.0.3 on 2026-04-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLVBDH', '0022_noinhan_alter_xuly_vai_tro_ky_luanchuyenbenngoai'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanbanden',
            name='da_ban_hanh_noi_bo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vanbandi',
            name='da_ban_hanh_noi_bo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vanbandi',
            name='da_gui_phan_cong',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vanbandi',
            name='da_phat_hanh_ben_ngoai',
            field=models.BooleanField(default=False),
        ),
    ]
