# Generated by Django 6.0.3 on 2026-04-18 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLVBDH', '0023_vanbanden_da_ban_hanh_noi_bo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vanbanden',
            name='file_van_ban',
            field=models.FileField(blank=True, null=True, upload_to='van_ban_den/'),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='ban_du_thao',
            field=models.FileField(blank=True, null=True, upload_to='van_ban_di/du_thao/'),
        ),
        migrations.CreateModel(
            name='TepDinhKemVanBanDen',
            fields=[
                ('ma_tep', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('tep_tin', models.FileField(upload_to='van_ban_den/')),
                ('thu_tu', models.PositiveIntegerField(default=0)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('so_vb_den', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tep_dinh_kems', to='QLVBDH.vanbanden')),
            ],
            options={
                'db_table': 'TepDinhKemVanBanDen',
                'ordering': ['thu_tu', 'ngay_tao', 'ma_tep'],
            },
        ),
        migrations.CreateModel(
            name='TepDinhKemVanBanDi',
            fields=[
                ('ma_tep', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('loai_tep', models.CharField(choices=[('du_thao', 'Du thao'), ('chinh_thuc', 'Chinh thuc')], max_length=20)),
                ('tep_tin', models.FileField(upload_to='van_ban_di/')),
                ('thu_tu', models.PositiveIntegerField(default=0)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('so_vb_di', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tep_dinh_kem_dis', to='QLVBDH.vanbandi')),
            ],
            options={
                'db_table': 'TepDinhKemVanBanDi',
                'ordering': ['loai_tep', 'thu_tu', 'ngay_tao', 'ma_tep'],
            },
        ),
    ]
