from django.urls import path

from .views import (
    admin_login_redirect_view,
    ban_hanh_noi_bo_van_ban_di_view,
    ban_hanh_noi_bo_van_ban_den_view,
    cap_so_van_ban_di_view,
    cap_nhat_luan_chuyen_ben_ngoai_view,
    cap_nhat_tien_do_ca_nhan_view,
    cap_nhat_mau_van_ban_view,
    cap_nhat_ho_so_ca_nhan_view,
    cap_nhat_phan_quyen_nguoi_dung_view,
    cap_nhat_tai_khoan_giao_vien_view,
    cap_nhat_van_ban_den_view,
    cap_nhat_van_ban_di_view,
    can_phan_cong_view,
    chuyen_phan_cong_ca_nhan_view,
    chi_tiet_tien_do_view,
    da_phan_cong_view,
    danh_sach_mau_van_ban_view,
    danh_sach_van_ban_di_view,
    danh_sach_van_ban_den_view,
    dang_ky_van_ban_den_view,
    dang_ky_van_ban_di_view,
    dang_ky_van_ban_di_tu_danh_muc_view,
    danh_dau_da_gui_luan_chuyen_ben_ngoai_view,
    doi_mat_khau_ca_nhan_view,
    duyet_van_ban_di_action_view,
    duyet_van_ban_view,
    danh_sach_noi_nhan_view,
    danh_sach_nguoi_dung_view,
    cap_nhat_noi_nhan_view,
    home_view,
    login_view,
    luu_phan_cong_xu_ly_view,
    luan_chuyen_van_ban_di_view,
    logout_view,
    hoan_thanh_chinh_sua_van_ban_view,
    phan_cong_xu_ly_van_ban_di_view,
    phat_hanh_ben_ngoai_van_ban_di_view,
    phan_quyen_nguoi_dung_view,
    reset_mat_khau_giao_vien_view,
    tao_van_ban_view,
    them_noi_nhan_view,
    them_giao_vien_view,
    them_mau_van_ban_view,
    theo_doi_tien_do_view,
    theo_doi_tinh_trang_view,
    van_ban_da_ban_hanh_view,
    van_ban_da_tao_view,
    van_ban_phat_hanh_ben_ngoai_view,
    van_ban_tra_lai_view,
    van_ban_xu_ly_ca_nhan_view,
    xoa_mau_van_ban_view,
)


urlpatterns = [
    path("", home_view, name="home"),
    path("dang-nhap/", login_view, name="login"),
    path("dang-xuat/", logout_view, name="logout"),
    path("theo-doi-tinh-trang/", theo_doi_tinh_trang_view, name="theo_doi_tinh_trang"),
    path("quan-ly-cong-viec/duyet-van-ban/", duyet_van_ban_view, name="duyet_van_ban"),
    path("quan-ly-cong-viec/can-phan-cong/", can_phan_cong_view, name="can_phan_cong"),
    path("quan-ly-cong-viec/da-phan-cong/", da_phan_cong_view, name="da_phan_cong"),
    path("quan-ly-cong-viec/theo-doi-tien-do/", theo_doi_tien_do_view, name="theo_doi_tien_do"),
    path("quan-ly-cong-viec/theo-doi-tien-do/chi-tiet/", chi_tiet_tien_do_view, name="chi_tiet_tien_do"),
    path("quan-ly-cong-viec/phan-cong-xu-ly/", luu_phan_cong_xu_ly_view, name="luu_phan_cong_xu_ly"),
    path("cong-viec-ca-nhan/van-ban-xu-ly/", van_ban_xu_ly_ca_nhan_view, name="van_ban_xu_ly_ca_nhan"),
    path("cong-viec-ca-nhan/van-ban-tra-lai/", van_ban_tra_lai_view, name="van_ban_tra_lai"),
    path("cong-viec-ca-nhan/xu-ly/<str:ma_xu_ly>/cap-nhat/", cap_nhat_tien_do_ca_nhan_view, name="cap_nhat_tien_do_ca_nhan"),
    path("cong-viec-ca-nhan/xu-ly/<str:ma_xu_ly>/chuyen-phan-cong/", chuyen_phan_cong_ca_nhan_view, name="chuyen_phan_cong_ca_nhan"),
    path("cong-viec-ca-nhan/van-ban-tra-lai/<str:so_vb_di>/hoan-thanh/", hoan_thanh_chinh_sua_van_ban_view, name="hoan_thanh_chinh_sua_van_ban"),
    path("danh-sach-van-ban/da-ban-hanh/", van_ban_da_ban_hanh_view, name="van_ban_da_ban_hanh"),
    path("danh-sach-van-ban/da-tao/", van_ban_da_tao_view, name="van_ban_da_tao"),
    path("danh-sach-van-ban/phat-hanh-ben-ngoai/", van_ban_phat_hanh_ben_ngoai_view, name="van_ban_phat_hanh_ben_ngoai"),
    path("tao-van-ban/", tao_van_ban_view, name="tao_van_ban"),
    path("ho-so-ca-nhan/cap-nhat/", cap_nhat_ho_so_ca_nhan_view, name="cap_nhat_ho_so_ca_nhan"),
    path("ho-so-ca-nhan/doi-mat-khau/", doi_mat_khau_ca_nhan_view, name="doi_mat_khau_ca_nhan"),
    path("quan-ly-tai-khoan/danh-sach-nguoi-dung/", danh_sach_nguoi_dung_view, name="danh_sach_nguoi_dung"),
    path("quan-ly-noi-nhan/", danh_sach_noi_nhan_view, name="danh_sach_noi_nhan"),
    path("quan-ly-noi-nhan/them/", them_noi_nhan_view, name="them_noi_nhan"),
    path("quan-ly-noi-nhan/<str:ma_noi_nhan>/cap-nhat/", cap_nhat_noi_nhan_view, name="cap_nhat_noi_nhan"),
    path("quan-ly-tai-khoan/them-giao-vien/", them_giao_vien_view, name="them_giao_vien"),
    path("quan-ly-tai-khoan/phan-quyen-nguoi-dung/", phan_quyen_nguoi_dung_view, name="phan_quyen_nguoi_dung"),
    path("quan-ly-tai-khoan/<str:ma_gv>/cap-nhat/", cap_nhat_tai_khoan_giao_vien_view, name="cap_nhat_tai_khoan_giao_vien"),
    path("quan-ly-tai-khoan/<str:ma_gv>/reset-mat-khau/", reset_mat_khau_giao_vien_view, name="reset_mat_khau_giao_vien"),
    path("quan-ly-tai-khoan/<str:ma_gv>/phan-quyen/", cap_nhat_phan_quyen_nguoi_dung_view, name="cap_nhat_phan_quyen_nguoi_dung"),
    path("mau-van-ban/", danh_sach_mau_van_ban_view, name="danh_sach_mau_van_ban"),
    path("mau-van-ban/them/", them_mau_van_ban_view, name="them_mau_van_ban"),
    path("mau-van-ban/<str:ma_mau_vb>/cap-nhat/", cap_nhat_mau_van_ban_view, name="cap_nhat_mau_van_ban"),
    path("mau-van-ban/<str:ma_mau_vb>/xoa/", xoa_mau_van_ban_view, name="xoa_mau_van_ban"),
    path("van-ban-den/", danh_sach_van_ban_den_view, name="danh_sach_van_ban_den"),
    path("van-ban-di/", danh_sach_van_ban_di_view, name="danh_sach_van_ban_di"),
    path("van-ban-den/dang-ky/", dang_ky_van_ban_den_view, name="dang_ky_van_ban_den"),
    path("van-ban-di/dang-ky/", dang_ky_van_ban_di_tu_danh_muc_view, name="dang_ky_van_ban_di_tu_danh_muc"),
    path("van-ban-di/<str:so_vb_di>/dang-ky/", dang_ky_van_ban_di_view, name="dang_ky_van_ban_di"),
    path("van-ban-di/<str:so_vb_di>/cap-so/", cap_so_van_ban_di_view, name="cap_so_van_ban_di"),
    path("van-ban-di/<str:so_vb_di>/luan-chuyen/", luan_chuyen_van_ban_di_view, name="luan_chuyen_van_ban_di"),
    path("van-ban-di/<str:so_vb_di>/phat-hanh-ben-ngoai/", phat_hanh_ben_ngoai_van_ban_di_view, name="phat_hanh_ben_ngoai_van_ban_di"),
    path("phat-hanh-ben-ngoai/<str:ma_luan_chuyen>/cap-nhat/", cap_nhat_luan_chuyen_ben_ngoai_view, name="cap_nhat_luan_chuyen_ben_ngoai"),
    path("phat-hanh-ben-ngoai/<str:ma_luan_chuyen>/da-gui/", danh_dau_da_gui_luan_chuyen_ben_ngoai_view, name="danh_dau_da_gui_luan_chuyen_ben_ngoai"),
    path("van-ban-di/<str:so_vb_di>/ban-hanh-noi-bo/", ban_hanh_noi_bo_van_ban_di_view, name="ban_hanh_noi_bo_van_ban_di"),
    path("van-ban-di/<str:so_vb_di>/phan-cong-xu-ly/", phan_cong_xu_ly_van_ban_di_view, name="phan_cong_xu_ly_van_ban_di"),
    path("van-ban-di/<str:so_vb_di>/duyet/", duyet_van_ban_di_action_view, name="duyet_van_ban_di_action"),
    path("van-ban-den/<str:so_vb_den>/cap-nhat/", cap_nhat_van_ban_den_view, name="cap_nhat_van_ban_den"),
    path("van-ban-den/<str:so_vb_den>/ban-hanh-noi-bo/", ban_hanh_noi_bo_van_ban_den_view, name="ban_hanh_noi_bo_van_ban_den"),
    path("van-ban-di/<str:so_vb_di>/cap-nhat/", cap_nhat_van_ban_di_view, name="cap_nhat_van_ban_di"),
    path("admin-login/", admin_login_redirect_view, name="admin_login_redirect"),
]
